# Generated by Django 5.2.6 on 2026-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_contact_delete_contactinfo_delete_herosection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('featured', 'Featured'), ('popular', 'Popular')], default='completed', max_length=20),
        ),
    ]
