# Generated by Django 5.2.6 on 2026-03-07 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-proficiency']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-rating', '-created_at']},
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('featured', 'Featured')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated list, e.g. Django,React,PostgreSQL', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g. fab fa-python', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50, help_text='Skill level from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
